server:
  port: 1993

spring:
  application:
    name: opv-gateway
  cloud:
    gateway:
      routes:
      - id: NewVehicleModule
        uri: lb://OPV-NEWVEHICLE
        predicates:
        - Path=/api/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka   
      instance:
      hostname: localhost            
     
        
       
